name: ZIP And Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Zip files
        run: |
          zip -r index.zip index.html favicon.png script.js style.css

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: index.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-tag:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create a tag
        run: |
          git tag v.auto.generated
          git push origin v.auto.generated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
